---
title: An Update on the SunPy Project
subtitle: PyHC Fall Meeting / Hybrid / 11 Nov 2024
authors:
- Will Barnes
- Stuart Mumford
- Nabil Freij
institute:
- AU/NASA GSFC
- Aperio Software
- SETI Institute
format:
  revealjs:
    code-line-numbers: false
    margin: 0
    width: 100%
    height: 100%
    theme: [default, theme/sunpy-theme.scss]
    logo: static/sunpy_logo_landscape.png
title-slide-attributes:
  data-background-image: static/sunpy_icon.svg
  data-background-position: -100% 50%
  data-background-opacity: 50%
  data-background-size: 80%
---
```{python}
#| echo: false
#| eval: true
import os
os.environ["PARFIVE_HIDE_PROGRESS"] = "True"

import sunpy
sunpy.log.setLevel('ERROR')
```

## What's New in The SunPy Project? {background-image="static/sunpy_icon.svg" background-size="70%" background-opacity="50%"}

- v6.0 Released - **June 2024**
- v6.1 coming - **December 2024**
- Further improvements to automated templating and packaging guide
- Overhaul of the SunPy Project Governance
- ROSES OSTFL 2024 Funding Awarded

## `sunpy` v6.0 {background-image="static/sunpy_icon.svg" background-size="70%" background-opacity="50%"}

- New features in v6.0 include:
    - Overhaul of optional dependencies
    - Decoupling dates in Map
    - Support for ADvanced Adaptive Prediction Technique (ADAPT) data - Map and Fido
    - New PlanarScreen context manager
    - Method to compute the rotation matrix between two SPICE frames
    - Removal of deprecated features and updated minimum dependencies
- By the numbers:
  - Since v5.1: 795 commits in 177 merged pull requests closing 67 issues.
  - 34 contributors, **16 of whom are new contributors**
- Full details here: [docs.sunpy.org/en/stable/whatsnew](https://docs.sunpy.org/en/stable/whatsnew)

## `sunpy` v6.1 {background-image="static/sunpy_icon.svg" background-size="70%" background-opacity="50%"}

- New features that will be in v6.1 include:
    - Improving HEK Representation within Fido
    - Support for Helioprojective Radial Frame
    - URI handling in Map and Timeseries
    - Save support for ASDF
    - Ability to draw the extent of another WCS on top of a Map.
    - Removal of deprecated features and updated minimum dependencies

## The SunPy Package Template

- Updated OpenAstronomy packaging guide: [packaging-guide.openastronomy.org](https://packaging-guide.openastronomy.org)
  - Narrative documentation describing how to structure a package
  - [`cruft`](https://cruft.github.io/) to [automate updates](https://github.com/sunpy/sunkit-magex/pull/16) to packages when template changes
  - ```shell
  cruft create github.com/OpenAstronomy/packaging-guide
  ```

- OpenAstronomy template + SunPy specific functionality == SunPy Package Template [github.com/sunpy/package-template](https://github.com/sunpy/package-template)
  - Enable automatic packaging, linting and other configuration updates over all SunPy-maintained packages.
  - Bot workflow allows weekly updates from the central repository using Pull requests
  - Greatly simplified maintenance of 10+ repositories

## Overhaul of the SunPy Project Governance

- Previous structure: Self electing Board who appointed key personal like the Lead Developer
- There was a year long process to rewrite SEP-2 to define a new structure
- New structure:
    - Self-electing Project Custodians based on positive record of contribution to the project.
    - 3 person Steering Committee, elected by the custodians.
    - Self Electing Advisory Board (still a WIP)
- Steering Committee Elected
     - Stuart Mumford
     - Laura Hayes
     - Albert Shih

## ROSES OSTFL 2024 Funding Awarded

- (Co-)PIs: Albert Shih, Will Barnes, Stuart Mumford, Sam Badman and Kris Cooper
- Project wide documentation improvements: cross-project example gallery, documentation layout and project wide tutorial.
- New Features and Improvements to sunkit-spex (X-ray Spectroscopy)
- New Features and Improvements to sunkit-magex (Magnetic Field Extrapolations)
- General SunPy maintenance
